adding function to insert new values to toml table
alexcrichton/toml-rs pull request #233
Opened 2018-04-12 12:34 UTC by jaroslaw-weber

I implement inserting new values directly into the Value.
I wrote about it in an Issue here:
https://github.com/alexcrichton/toml-rs/issues/231

We can already quickly get values from Value with index access, but inserting the new Value is kind of clunky, so I added the helper function directly inside the Value.

2018-04-12 15:18 UTC, dtolnay requested changes
I would prefer not to have this method and instead recommend that people manipulate `toml::value::Table` rather than `Value` if they want to write code like this. I believe the code in your test case is clearer if written using Table and not Value.

```rust
let mut t: Table = toml::from_str("a=1").expect("failed to create Table");
t.insert("b".to_owned(), Value::Integer(2));
t.insert("c".to_owned(), Value::Integer(3));
```

2018-04-13 00:52 UTC, jaroslaw-weber commented
@dtolnay 
hey, thanks for the feedback! I understand your point of view, writing `as_mut_table().unwrap().insert(...)` is not that much longer and there is a way to insert a value already so it is not that necessary. Still, I miss inserting values with index just like in serde. I think it is common operation and it is worth to consider adding inserting directly in the Value.

2018-04-13 00:56 UTC, dtolnay commented
Maybe I have not used the toml crate enough myself to have hit this use case -- could you point out an example of real code that would benefit from having Value::insert?

2018-04-13 01:06 UTC, jaroslaw-weber commented
@dtolnay 
I edited my post, please read it again!
I was using serde json before and was confused why cannot I directly inserting things into Value (in json you can insert to value with index) and was doing it like this:
```
let mut t: Value = toml::from_str("a=1").expect("failed to create Value");
t.as_mut_table().unwrap().insert("b".to_owned(), Toml::Integer(1));
```
and this was little long so I thought we could use inserting new Value directly in the Value.

But toml crate is little different, I didn't know you are supposed to do:
```
let mut t: Table = toml::from_str("a=1").expect("failed to create Table");
```

So I agree with you, we don't need adding insert method in the Value. But I would add inserting example to readme/docs, because it is quite common pattern and people who used serde json may find it little confusing.

2018-04-13 16:09 UTC, alexcrichton commented
Adding some examples to the documentation sounds great to me as well!

2022-09-23 16:02 UTC, epage commented
toml-rs has moved to https://github.com/toml-rs/toml_edit.  Feel free to rebase your PR against that repo and open a new issue there.

2022-09-23 16:02 UTC, closed without merging